import { AvatarTags } from "@/utils/index";

export const AvatarBaseImages = [
    {
        title: "Sample Avatars",
        tags: [AvatarTags.female, AvatarTags.models, AvatarTags.fantasy],
        items: [
            "/assets/presets/villa.jpeg",
            "/assets/presets/river_goddess.jpeg",
            "/assets/elvenmage-4.jpeg",
            "/assets/avatar-bases/angel_eyes.jpeg",
            "/assets/avatar-bases/red_bikini_lounge.jpeg",
        ],
    },
    {
        title: "Female Avatars",
        tags: [AvatarTags.female, AvatarTags.models, AvatarTags.fantasy],
        items: [
            "/assets/avatar-bases/angel_eyes.jpeg",
            "/assets/avatar-bases/red_bikini_lounge.jpeg",
            "/assets/avatar-bases/look_back.jpeg",
            "/assets/avatar-bases/sports1.jpeg",
            "/assets/avatar-bases/baseballcap.jpeg",
            "/assets/avatar-bases/beach_67.jpeg",
            "/assets/avatar-bases/beach_77.jpeg",
            "/assets/avatar-bases/bedroom_eyes.jpeg",
            "/assets/avatar-bases/club_2.jpeg",
            "/assets/avatar-bases/business_girl_1.jpeg",
            "/assets/avatar-bases/business-girl_2.jpeg",
            "/assets/avatar-bases/daance.jpeg",
            "/assets/avatar-bases/dinner.jpeg",
            "/assets/avatar-bases/doc.jpeg",
            "/assets/avatar-bases/exercise_1.jpeg",
            "/assets/avatar-bases/exercise_9.jpeg",
            "/assets/avatar-bases/flannel_1.jpeg",
            "/assets/avatar-bases/glam_7.jpeg",
            "/assets/avatar-bases/sunny.jpeg",
            "/assets/avatar-bases/surfer_chick.jpeg",
            "/assets/avatar-bases/the_fair.jpeg",
            "/assets/avatar-bases/tire_swing.jpeg",
            "/assets/avatar-bases/volleyball.jpeg",
        ],
    },
    {
        title: "Female Fantasy Avatars",
        tags: [AvatarTags.female, AvatarTags.models, AvatarTags.fantasy],
        items: [
            "/assets/presets/blue_sorceress.jpeg",
            "/assets/presets/slyvan_priestess.jpeg",
            "/assets/presets/villa.jpeg",
            "/assets/presets/temple_priestess.jpeg",
            "/assets/presets/river_goddess.jpeg",
            "/assets/elvenmage-4.jpeg",
            "/assets/avatar-bases/smiles_braids.jpeg",
            "/assets/avatar-bases/gothic_mistress.jpeg",
            "/assets/avatar-bases/archer_4.jpeg",
            "/assets/avatar-bases/druidess.jpeg",
            "/assets/avatar-bases/the_good_witch.jpeg",
            "/assets/avatar-bases/cyber_lock.jpeg",
            "/assets/avatar-bases/relaxed_rogue.jpeg",
            "/assets/avatar-bases/blode_warrior.jpeg",
            "/assets/avatar-bases/brazier_and_sword.jpeg",
            "/assets/avatar-bases/relaxed_rogue.jpeg",
            "/assets/avatar-bases/cyber_6.jpeg",
            "/assets/avatar-bases/druidess_3.jpeg",
            "/assets/avatar-bases/green9.jpeg",
            "/assets/avatar-bases/lake_7.jpeg",
            "/assets/avatar-bases/leaning_rogue.jpeg",
            "/assets/avatar-bases/library.jpeg",
            "/assets/avatar-bases/ranger.jpeg",
            "/assets/avatar-bases/red_lake.jpeg",
            "/assets/avatar-bases/red_photo_shoot.jpeg",
            "/assets/avatar-bases/rogue_sexy9.jpeg",
            "/assets/avatar-bases/rogue_stone.jpeg",
            "/assets/avatar-bases/sexy_warlock.jpeg",
            "/assets/avatar-bases/shaman.jpeg",
            "/assets/avatar-bases/shaman2.jpeg",
            "/assets/avatar-bases/viking_beauty_8.jpeg",
            "/assets/avatar-bases/viking_goddess_1.jpeg",
            "/assets/avatar-bases/viking_queen.jpeg",
            "/assets/avatar-bases/witch_8.jpeg",
        ],
    },
    {
        title: "Female Historical Avatars",
        tags: [],
        items: [
            "/assets/avatar-bases/oil_painting_4.jpeg",
            "/assets/avatar-bases/peasant_3.jpeg",
            "/assets/avatar-bases/pricness_oil.jpeg",
            "/assets/avatar-bases/princess.jpeg",
            "/assets/avatar-bases/typist.jpeg",
            "/assets/avatar-bases/vintage_nurse.jpeg",
        ],
    },
    {
        title: "Female Vintage Avatars",
        tags: [],
        items: [
            "assets/avatar-bases/studen_100.jpeg",
            "assets/avatar-bases/taking_notes_vintage.jpeg",
            "assets/avatar-bases/teacher_3.jpeg",
            "assets/avatar-bases/teacher_4.jpeg",
            "assets/avatar-bases/vintage_cheer.jpeg",
            "assets/avatar-bases/vintage_pinup.jpeg",
            "assets/avatar-bases/vintage_yearbook.jpeg",
            "assets/avatar-bases/yearbook_4.jpeg",
            "assets/avatar-bases/army7889.jpeg",
            "assets/avatar-bases/officer_4.jpeg",
        ],
    },
    {
        title: "Historical Male Avatars",
        tags: [],
        items: [
            "/assets/avatar-bases/cavalry_colonel.jpeg",
            "/assets/avatar-bases/civil_war_99.jpeg",
            "/assets/avatar-bases/general_civil_war.jpg",
            "/assets/avatar-bases/general.jpeg",
            "/assets/avatar-bases/general.jpg",
            "/assets/avatar-bases/generaldude.jpeg",
            "/assets/avatar-bases/rlee_general.png",
            "/assets/avatar-bases/mil_portrait.jpeg",
            "/assets/avatar-bases/military_4.jpeg",
            "/assets/avatar-bases/napoleonic.jpeg",
            "/assets/avatar-bases/old_officer.jpeg",
            "/assets/avatar-bases/ww1_89.jpeg",
        ],
    },
    {
        title: "Male RPG Avatars",
        tags: [],
        items: [
            "/assets/avatar-bases/old_monk.jpeg",
            "/assets/avatar-bases/artificer_2.jpeg",
            "/assets/avatar-bases/beefy_fighter.jpeg",
            "/assets/avatar-bases/future_soldier.jpeg",
            "/assets/avatar-bases/male_viking_2.jpeg",
            "/assets/avatar-bases/alchemist.jpeg",
            "/assets/avatar-bases/alchemist4.jpeg",
            "/assets/avatar-bases/armor_barb.jpeg",
            "/assets/avatar-bases/male_rogue.jpeg",
            "/assets/avatar-bases/shaggy.jpeg",
            "/assets/avatar-bases/sword_and_board.jpeg",
            "/assets/avatar-bases/sword_fighter.jpeg",
            "/assets/avatar-bases/undergrtound.jpeg",
        ],
    },
    {
        title: "Male Vintage Avatars",
        tags: [],
        items: [
            "/assets/avatar-bases/army_88.jpeg",
            "/assets/avatar-bases/army_diner.jpeg",
            "/assets/avatar-bases/farmer_vintage.jpeg",
            "/assets/avatar-bases/fat_lawyer.jpeg",
            "/assets/avatar-bases/fat_run.jpeg",
            "/assets/avatar-bases/fat_shake.jpeg",
            "/assets/avatar-bases/handsome_lawyer.jpeg",
            "/assets/avatar-bases/officer009.jpeg",
            "/assets/avatar-bases/quarterback.jpeg",
            "/assets/avatar-bases/running_back.jpeg",
            "/assets/avatar-bases/student_34.jpeg",
            "/assets/avatar-bases/student.jpeg",
            "/assets/avatar-bases/sumo_3.jpeg",
            "/assets/avatar-bases/vintage_sailor.jpeg",
        ],
    },
    {
        title: "Male Avatars",
        tags: [],
        items: [
            "/assets/avatar-bases/army_1.jpeg",
            "/assets/avatar-bases/captain.jpeg",
            "/assets/avatar-bases/agent.jpeg",
            "/assets/avatar-bases/business.jpeg",
            "/assets/avatar-bases/doctor.jpeg",
            "/assets/avatar-bases/eatcake.jpeg",
            "/assets/avatar-bases/office_man_2.jpeg",
            "/assets/avatar-bases/office-guy.jpeg",
            "/assets/avatar-bases/ranger_4.jpeg",
            "/assets/avatar-bases/riding.jpeg",
        ],
    },
];
