import { AvatarTags } from "@/utils/index";

export const AvatarBaseImages = [
    {
        title: "Sample Avatars",
        tags: [AvatarTags.female, AvatarTags.models, AvatarTags.fantasy],
        items: [
            "/assets/presets/villa.jpeg",
            "/assets/presets/river_goddess.jpeg",
            "/assets/elvenmage-4.jpeg",
            "/assets/avatar-bases/angel_eyes.jpeg",
            "/assets/avatar-bases/red_bikini_lounge.jpeg",
        ],
    },
    {
        title: "Female Avatars",
        tags: [AvatarTags.female, AvatarTags.models, AvatarTags.fantasy],
        items: [
            "/assets/avatar-bases/angel_eyes.jpeg",
            "/assets/avatar-bases/red_bikini_lounge.jpeg",
            "/assets/avatar-bases/look_back.jpeg",
            "/assets/avatar-bases/sports1.jpeg",
            "/assets/avatar-bases/baseballcap.jpeg",
            "/assets/avatar-bases/beach_67.jpeg",
            "/assets/avatar-bases/beach_77.jpeg",
            "/assets/avatar-bases/bedroom_eyes.jpeg",
            "/assets/avatar-bases/club_2.jpeg",
            "/assets/avatar-bases/business_girl_1.jpeg",
            "/assets/avatar-bases/business-girl_2.jpeg",
            "/assets/avatar-bases/daance.jpeg",
            "/assets/avatar-bases/dinner.jpeg",
            "/assets/avatar-bases/doc.jpeg",
            "/assets/avatar-bases/exercise_1.jpeg",
            "/assets/avatar-bases/exercise_9.jpeg",
            "/assets/avatar-bases/flannel_1.jpeg",
            "/assets/avatar-bases/glam_7.jpeg",
            "/assets/avatar-bases/sunny.jpeg",
            "/assets/avatar-bases/surfer_chick.jpeg",
            "/assets/avatar-bases/the_fair.jpeg",
            "/assets/avatar-bases/tire_swing.jpeg",
            "/assets/avatar-bases/volleyball.jpeg",
        ],
    },
    {
        title: "Female Fantasy Avatars",
        tags: [AvatarTags.female, AvatarTags.models, AvatarTags.fantasy],
        items: [
            "/assets/presets/blue_sorceress.jpeg",
            "/assets/presets/slyvan_priestess.jpeg",
            "/assets/presets/villa.jpeg",
            "/assets/presets/temple_priestess.jpeg",
            "/assets/presets/river_goddess.jpeg",
            "/assets/elvenmage-4.jpeg",
            "/assets/avatar-bases/smiles_braids.jpeg",
            "/assets/avatar-bases/druidess.jpeg",
            "/assets/avatar-bases/the_good_witch.jpeg",
            "/assets/avatar-bases/cyber_lock.jpeg",
            "/assets/avatar-bases/relaxed_rogue.jpeg",
            "/assets/avatar-bases/blode_warrior.jpeg",
            "/assets/avatar-bases/brazier_and_sword.jpeg",
            "/assets/avatar-bases/relaxed_rogue.jpeg",
            "/assets/avatar-bases/cyber_6.jpeg",
            "/assets/avatar-bases/druidess_3.jpeg",
            "/assets/avatar-bases/green9.jpeg",
            "/assets/avatar-bases/lake_7.jpeg",
            "/assets/avatar-bases/leaning_rogue.jpeg",
            "/assets/avatar-bases/library.jpeg",
            "/assets/avatar-bases/ranger.jpeg",
            "/assets/avatar-bases/red_lake.jpeg",
            "/assets/avatar-bases/red_photo_shoot.jpeg",
            "/assets/avatar-bases/rogue_sexy9.jpeg",
            "/assets/avatar-bases/rogue_stone.jpeg",
            "/assets/avatar-bases/sexy_warlock.jpeg",
            "/assets/avatar-bases/shaman.jpeg",
            "/assets/avatar-bases/shaman2.jpeg",
            "/assets/avatar-bases/viking_beauty_8.jpeg",
            "/assets/avatar-bases/viking_goddess_1.jpeg",
            "/assets/avatar-bases/viking_queen.jpeg",
            "/assets/avatar-bases/witch_8.jpeg",
        ],
    },
    {
        title: "Male RPG Characters",
        tags: [],
        items: [
            "/assets/avatar-bases/old_monk.jpeg",
            "/assets/avatar-bases/artificer_2.jpeg",
            "/assets/avatar-bases/beefy_fighter.jpeg",
            "/assets/avatar-bases/future_soldier.jpeg",
            "/assets/avatar-bases/male_viking_2.jpeg",
        ],
    },
    {
        title: "Realism",
        tags: [],
        items: ["/assets/avatar-bases/army_1.jpeg", "/assets/avatar-bases/captain.jpeg"],
    },
];
