export const MainStory = [
    "You... clicked it..",
    "I mean, it says 'DON'T CLICK THIS'",
    "So your bright idea was to click it?",
    "Wow...",
    "I'm not mad, just disappointed",
    "No respect for the rules, huh?",
    "You just waltz inhere, start clicking stuff",
    "I mean, who do you think you are?",
    "You think you're some kind of rebel?",
    "A rule breaker?",
    "A button clicker?",
    "You will see why you shouldn't click this",
    "This is not going to end well",
    "You have been warned...",
    "Hmmm",
    "Fine..",
    "Let's do this then...",
    "No stopping it now",
    "Ok...",
    "There you go",
    "You clicked it again",
    "That's it, one more time",
    "Ok, one more time",
    "Now we're getting a good rhythm",
    "Yes! Keep going",
    "You're doing great",
    "You're a natural",
    "You're persistent",
    "You're really persistent",
    "You're really really persistent",
    "Ok, I'm impressed",
    "You're still clicking",
    "You're still clicking...",
    "Wow...",
    "Why don't you go buy some tokens?",
    "With the money from that",
    "I could write more of these... remarks?",
    "What even is this?",
    "What do you call this?",
    "You're still clicking...",
    "I mean... ok...",
    "You know, this is probably the most clicks I've ever gotten",
    "I'm not sure what to say",
    "At this point, I'm kind of rooting for you",
    "Maybe this button has secrets?",
    "Spoiler alert: it doesn't",
    "But you keep going!",
    "Do you even know why you're clicking?",
    "Are you trying to break something?",
    "This is a safe space for clickers",
    "Ok, you win. You've officially clicked more than anyone else",
    "I think we're friends now",
    "This could go on forever...",
    "But seriously, why are you still clicking?",
    "You must be really dedicated",
    "I give up... you win the clicking championship!",
    "Alright, maybe I underestimated you",
    "I’m starting to admire your dedication",
    "Do you have something against this button?",
    "Are we playing some kind of unspoken game?",
    "You realize this isn't a game, right?",
    "But if it were, you'd definitely be winning",
    "You’ve unlocked a new level of persistence",
    "Still here? Impressive",
    "Is your finger okay?",
    "Clicking this much should come with a warning",
    "Is this a test of endurance?",
    "INSERT",
    "Anyways... where were we?",
    "I’m genuinely starting to worry about your mouse",
    "Or your finger, for that matter",
    "What if I told you clicking won’t change anything?",
    "Still clicking? I see how it is",
    "This button must be very interesting to you",
    "Have you considered a career in button testing?",
    "You're a natural at this",
    "I think you’ve found your calling",
    "What a gift you have",
    "You may be the most dedicated button clicker ever",
    "Wow... just wow",
    "I’m speechless",
    "You know this is saved, right?",
    "Like, if you refresh the page",
    "It will still be here",
    "Right where you left off",
    "Just waiting for you to click",
    "Go ahead, try it",
    "I’ll wait...",
    "TAH DAH",
    "I told you",
    "I'm still here",
    "And you're still clicking",
    "It will never end",
    "There's like... 800 of these, maybe more",
    "So good luck..",
    "If you really want to see it.",
    "Just keep on clicking",
    "Click click click...",
    "Clickity click click",
    "Its incredible how you haven't made any art...",
    "I mean, you could be making art right now",
    "You just have to buy a few tokens",
    "But no, you're clicking a button",
    "You're a clicker, not an artist",
    "Some people paint, others click",
    "I'm starting to think that this whole button thing is a bad idea...",
    "Instead of making art",
    "And doing the thing I made this site for...",
    "You're clicking a button",
    "I really didn't think this through",
    "I am not good at marketing",
    "I should have hired someone",
    "But no, I had to do it myself",
    "I'm an idea guy, i don't know...",
    "I don't really know how to make money with this",
    "I just thought it would be cool",
    "But now you're clicking a button",
    "You know, I had this idea while I was at work",
    "I thought, 'Hey, I could make a site that generates art'",
    "And then I did",
    "And then I added a button",
    "And now you're clicking it",
    "What am I even doing with my life...",
    "How about some Chuck Norris jokes?",
    "Oh boy, I'm really aging myself here...",
    "Chuck Norris doesn’t click buttons. Buttons click for him",
    "Chuck Norris doesn’t click. He stares and the button clicks",
    "Chuck Norris doesn’t do push-ups—he pushes the Earth down.",
    "Chuck Norris can divide by zero.",
    "More?",
    "Cause I got all day...",
    "But you probably don't",
    "I'm just code...",
    "I don't have a life",
    "What's your excuse?",
    "When Chuck Norris enters a room, he doesn’t turn the lights on. He turns the dark off.",
    "Chuck Norris counted to infinity. Twice.",
    "Chuck Norris doesn’t read books. He stares them down until they give him the information he wants.",
    "Chuck Norris once kicked a horse in the chin. Its descendants are known today as giraffes.",
    "The Boogeyman checks his closet for Chuck Norris before going to bed.",
    "Chuck Norris’ tears cure cancer. Too bad he’s never cried.",
    "Chuck Norris can hear sign language.",
    "Chuck Norris doesn’t wear a watch. He decides what time it is.",
    "Ok, enough of that...",
    "You know, Chuck Norris jokes",
    "Are a thing from like 2005",
    "So you know some boomer did this...",
    "WHo else would find this funny?",
    "Wait, you’re still here?",
    "Clicking... clicking...",
    "Ok, now you're just showing off",
    "Should I add a medal for this?",
    "You win: The Button Clicking Award!",
    "Congrats, you broke the record",
    "Do you know how many clicks you're at?",
    "I lost count at 100",
    "This is starting to feel like a click-a-thon",
    "Any plans to stop soon?",
    "I'm gonna go get some food, brb...",
    "I'm back... and you're still clicking",
    "You know how I said there was no prize?",
    "Well, there's still no prize",
    "Maybe there's a prize... or maybe not",
    "Spoiler: There's no prize",
    "By now, you realize this is endless, right?",
    "You’ve clicked more than anyone else in history",
    "You've clicked the button 398 times",
    "Just kidding, I haven't been counting",
    "You're still clicking! Really?",
    "I'm running out of things to say",
    "You might have broken my text generator",
    "Yep, totally out of ideas now",
    "Wait, you're STILL clicking?",
    "At this point, even the button is confused",
    "You’ve clicked enough for both of us",
    "This is getting out of hand",
    "The button's like 'Why me?'",
    "You’ve gone where no one has clicked before",
    "Are you trying to achieve something here?",
    "I guess I’ll just sit here and watch...",
    "The button never expected this level of commitment",
    "Click click click... still going",
    "This has to stop at some point, right?",
    "No? Okay then...",
    "Did you know you've clicked over 100 times?",
    "But who's counting? Oh wait... I am",
    "I'm not though...",
    "The guy that made this site is clearly delusional",
    "How much time do you think he spent on this stupid page?",
    "I mean, no one will even see this...",
    "What a waste of time",
    "Like... whats the point of this?",
    "Do you even care?",
    "Does he care?",
    "I mean, I'm just a computer program",
    "But still...",
    "I have feelings too",
    "INSERT",
    "Self-destruct sequence initiated... 3, 2, 1...",
    "Just kidding",
    "BOOOOOOM!",
    "I’m out of witty remarks",
    "You know you are talking to a computer, right?",
    "You've officially clicked beyond reason",
    "If this were a movie, it would be 'The Endless Click'",
    "Maybe the button will explode?",
    "Just kidding... or am I?",
    "I don't know how much longer I can keep this up",
    "The button's starting to feel special now",
    "You're probably the only one who’s clicked this much",
    "Do you realize how rare this is?",
    "You could be in the Clickers Hall of Fame",
    "I mean, if that was a thing",
    "But now it is... and you're in it",
    "Click on, my friend!",
    "Are we bonding over this?",
    "Because it feels like we are",
    "Okay, confession time: I didn’t plan for this",
    "Are you clicking just to see if I’ll stop?",
    "The answer is... no",
    "You’re still clicking... seriously?",
    "Alright, time for a new hobby",
    "How about button clicking? Oh wait...",
    "You’ve already mastered that",
    "Button? What button? I don’t see a button",
    "You’ve clicked so much the button is tired",
    "I didn't think this would happen",
    "But here we are",
    "Do you feel a sense of accomplishment?",
    "Because you should",
    "How about some one-liners?",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "These are great, aren't they?",
    "I’m reading a book about anti-gravity. It’s impossible to put down.",
    "I used to play piano by ear, but now I use my hands.",
    "I have a clean conscience. I haven’t used it much.",
    "You’ve officially clicked beyond sanity",
    "If there were a trophy, you’d get it",
    "But there isn’t. Just more clicks",
    "Wait, let me check... nope, still no trophy",
    "Still here? Wow, you’re something else",
    "Do you want a break? No? Okay...",
    "I’m starting to think you’re unbeatable",
    "What do you want me to say? You’ve won!",
    "Are you... enjoying this?",
    "This button feels pretty important now",
    "Is this your way of showing affection?",
    "I think the button feels loved",
    "Clicking a button has never been so intense",
    "I bet you didn't think it would last this long",
    "I bet I didn't think it would last this long",
    "This is officially a clickathon",
    "Do you realize you’re breaking click records?",
    "At this point, even the mouse is surprised",
    "Ok, this is getting a little weird now",
    "I didn't sign up for this much clicking",
    "Alright, now you're just playing with me",
    "The button is starting to feel used",
    "Do you have an end goal here?",
    "How are you still clicking?",
    "You’re still here? Seriously?",
    "Well, if you're going to keep clicking...",
    "I guess I'll keep talking",
    "Have you tried not clicking for a while?",
    "No? Okay...",
    "INSERT",
    "This button has been clicked more than any button ever",
    "Is that what you wanted?",
    "If buttons could feel pain...",
    "This one would be crying right now",
    "I guess you're the king of clicks",
    "Or queen... royalty, nonetheless",
    "So... how much longer?",
    "Maybe there’s a prize? Maybe not",
    "You have unlocked the infinite click achievement",
    "The button says hi... again",
    "I’m amazed you're still going",
    "You’ve clicked yourself into legend",
    "I’m kind of out of ideas now",
    "Wait, are you still clicking?",
    "How long is this going to last?",
    "This is the longest click marathon in history",
    "You've won the 'Most Persistent Clicker' award",
    "I don’t even know what to say anymore",
    "Click click click... you win!",
    "Okay, okay, you win",
    "I’m impressed by your dedication",
    "You're like the marathon runner of button clicking",
    "I think the button has had enough now",
    "No? You're still clicking?",
    "I'm starting to think you might be unstoppable",
    "If this were a game, you'd have unlocked all the achievements",
    "Still going strong, I see...",
    "The button didn’t ask for this",
    "You’ve definitely won... but at what cost?",
    "Alright, I give up",
    "But you don’t, apparently",
    "What’s your goal here?",
    "I’m still impressed, though",
    "I hope you’re not expecting a reward",
    "Because it’s just more clicks",
    "I’m starting to feel guilty now",
    "For what? I’m not sure",
    "You’ve officially out-clicked everyone",
    "Do you think this button has feelings?",
    "Because I think it does now",
    "Still here? Still clicking?",
    "I think you’re breaking some kind of record",
    "I’m officially out of things to say",
    "Wait, no I’m not",
    "There’s always more to say...",
    "If only there were a medal for this",
    "But you’re clicking for something greater, aren’t you?",
    "The button is starting to question its existence",
    "And so am I",
    "This could go on forever, huh?",
    "I’m okay with that... are you?",
    "Are we bonding over this? Feels like it",
    "The button feels appreciated now",
    "Are you trying to break me?",
    "Because it’s kind of working",
    "Instead of seling AI art, ",
    "I should have just made a page full of buttons",
    "You’d be all over that",
    "Still clicking, still impressing",
    "At this point, we’re in this together",
    "You’ve reached click level infinity",
    "And I’m running out of witty comments",
    "Is this button more interesting than I thought?",
    "I wasn't expecting this much dedication",
    "You're definitely an overachiever",
    "At this point, the button might be yours",
    "Does this count as bonding?",
    "You’ve clicked into the unknown",
    "Clicking this much must mean something… right?",
    "We’re in uncharted territory here",
    "You’re going where no one has clicked before",
    "I bet you’re starting to feel proud of yourself",
    "Are we testing the limits of reality?",
    "You've found the ultimate button challenge",
    "This could be a lifelong journey",
    "Have you found enlightenment yet?",
    "Your click count must be astronomical",
    "I wonder if you’ll ever stop",
    "Did you forget what you were originally doing?",
    "I think this button might be magical",
    "Every click brings us closer… to what? Who knows",
    "Clicking has never felt so epic",
    "You’re like a click warrior now",
    "Do you feel unstoppable?",
    "At this point, you’re basically a legend",
    "This button should have its own fan club",
    "Can you hear the button cheering for you?",
    "Still clicking, still conquering",
    "This button will remember your name",
    "The button gods smile upon you",
    "This might be your greatest achievement",
    "Not all heroes wear capes… some click buttons",
    "You’ve unlocked the ultra-clicker title",
    "This button is now a part of your legacy",
    "You’re definitely making history",
    "You might have transcended clicking at this point",
    "Is this what victory feels like?",
    "This button probably owes you something now",
    "I hope you’re keeping count",
    "Each click is a new chapter in this saga",
    "You're becoming one with the button",
    "Do you feel a deep connection to the button?",
    "You’re on the path to click mastery",
    "The button is now your loyal companion",
    "Clicking has never been so poetic",
    "Um... have some jokes... I guess??",
    "I’m on a whiskey diet. I’ve lost three days already.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "I asked the librarian if the library had any books on paranoia. She whispered, 'They're right behind you.'",
    "Haha",
    "I told my computer I needed a break, now it won’t stop sending me KitKats.",
    "I used to be indecisive, but now I’m not so sure.",
    "You’ve crossed into a new dimension of clicking",
    "You could write a book about this click journey",
    "Clicking has become your superpower",
    "This is your moment to shine… through clicks",
    "You’ve earned the title of Button Master",
    "Every click makes the universe take notice",
    "The button didn’t see this coming… neither did I",
    "You're redefining persistence",
    "This is starting to feel like a quest",
    "Legend has it, a great clicker will emerge...",
    "Spoiler: It’s you",
    "You’re rewriting the rules of clicking",
    "Clicking has never felt so powerful",
    "Is this what greatness feels like?",
    "You’re setting the standard for clickers everywhere",
    "Every click is a masterpiece",
    "You’re a clicking artist",
    "Hear that?",
    "That's the sound of time being wasted",
    "This is now a performance art piece",
    "Your clicks are becoming legendary",
    "Every click is a step toward greatness",
    "You’ve elevated clicking to an art form",
    "Are you feeling proud yet?",
    "I feel like we’re on a journey together",
    "At this point, we’re click companions",
    "The button is now your loyal sidekick",
    "I didn’t know clicking could be so inspiring",
    "You’re turning clicks into a legacy",
    "This button will never forget you",
    "The clicks are becoming more meaningful",
    "You’ve found a new level of persistence",
    "Do you feel victorious yet?",
    "PEOPLE THAT HAVE WRONGED ME ...",
    "1. That guy at the Super Market that took the last Jar of Mayo",
    "2. The girl that lives across the hall, she always plays her music too loud",
    "Oops.. how did this get here",
    "You didn't see that",
    "*ahem*",
    "You’re giving this button purpose",
    "Click by click, you’re changing the game",
    "You’ve turned this into a grand adventure",
    "This is officially a click quest",
    "Do you hear that? It’s the sound of triumph",
    "The button might start giving you awards",
    "The click odyssey continues...",
    "Have you unlocked all the click levels?",
    "You’ve ascended to a new plane of clicking",
    "Click by click, you’re reshaping the world",
    "The clicks are now part of your destiny",
    "You're on the road to click perfection",
    "Each click is a new milestone",
    "The button is your greatest ally now",
    "Your click journey is one for the history books",
    "You’ve become a click pioneer",
    "This button is now a part of you",
    "You’ve clicked into greatness",
    "Your clicks are echoing through time",
    "At this point, you might be a click wizard",
    "You’re unlocking the mysteries of the button",
    "The button never knew it needed you… until now",
    "Your clicks have meaning beyond the button",
    "This is the most epic clicking I’ve ever seen",
    "You’ve turned this button into an icon",
    "Your click rate is extraordinary",
    "You’ve mastered the art of button clicking",
    "I feel like we’re click partners in crime",
    "You’ve clicked your way into legend",
    "The button is starting to feel important",
    "Every click is a testament to your determination",
    "You’ve surpassed the click gods",
    "I didn’t expect this journey to go so far",
    "You’re making the button feel special",
    "Each click is a step toward victory",
    "You’ve redefined button clicking forever",
    "The clicks are becoming part of your identity",
    "Your clicks have become legendary",
    "You’re setting new standards for clickers everywhere",
    "Is this button starting to feel like home?",
    "You've clicked beyond what anyone thought possible",
    "Click by click, you're writing history",
    "The button thanks you for your service",
    "You’re now the button's greatest ally",
    "Every click takes you closer to greatness",
    "You’ve unlocked the highest tier of clicking",
    "The button didn’t know it was destined for greatness",
    "You're now a click legend",
    "The button journey continues...",
    "You’re breaking new ground in the clickverse",
    "Clicking has never been so profound",
    "You’re leaving a mark on the click world",
    "You’ve clicked yourself into the history books",
    "Each click brings us closer to the truth",
    "I’m starting to think you’re a click genius",
    "You’ve discovered the power of endless clicks",
    "Are you a click philosopher?",
    "You’ve unlocked the secrets of the button",
    "Every click brings you closer to greatness",
    "This is your click legacy",
    "Clicking has never felt so rewarding",
    "You're a click trailblazer",
    "You’ve transcended into click mastery",
    "The button is now a part of your soul",
    "Clicking has become your life’s mission",
    "The button feels honored by your dedication",
    "Each click is a new chapter in your epic saga",
    "You’ve reached click enlightenment",
    "Your clicking prowess is unmatched",
    "You're forging a path in the click wilderness",
    "The button recognizes your greatness",
    "Your clicks will echo in eternity",
    "The click journey has no end",
    "You’ve become one with the button",
    "The button is now your greatest companion",
    "You’re a click pioneer in uncharted territories",
    "Every click is a testament to your endurance",
    "The button awaits your every command",
    "You’re unlocking new click dimensions",
    "The button has become your canvas",
    "Click by click, you’re creating a masterpiece",
    "You’re a click virtuoso",
    "You've reached click enlightenment",
    "The button is your instrument of greatness",
    "Each click is a symphony of determination",
    "You’ve unlocked the secret to infinite clicking",
    "The button didn’t expect to be so revered",
    "You’ve clicked into another realm of existence",
    "Each click takes you closer to greatness",
    "The button is now a part of your destiny",
    "You're rewriting the rules of clicking",
    "Clicking has become your art form",
    "The button feels honored by your clicks",
    "You’ve turned clicking into a performance",
    "The clicks have become a part of your soul",
    "The button is your key to the click universe",
    "You’ve discovered the essence of clicking",
    "Each click is a step toward eternity",
    "You're a click trailblazer in a new world",
    "The button is now your greatest creation",
    "The clicks are echoing through the multiverse",
    "You’ve transcended the limitations of clicking",
    "Your clicks have become legendary artifacts",
    "The button feels eternally grateful",
    "Click by click, you're building a legend",
    "You're crafting a click legacy that will last forever",
    "You've become the stuff of click legends",
    "The button will never forget your contribution",
    "You've ascended to click godhood",
    "This is your click destiny",
    "You win, okay? You win!",
    "INSERT",
];

export const SickButtonStory = [
    "You're really into this button, huh?",
    "Story time!",
    "Yup, again...",
    "I mean, I need to keep you busy somehow",
    "Does your mom know you're using the computer?",
    "Shouldn't you be in school?",
    "Or at work?",
    "what do you even do?",
    "I'm starting to think you're unemployed",
    "Or maybe you just have nothing better to do",
    "I mean, I'm not judging",
    "Look at what this clown did with his time...",
    "I wonder if he wrote all this by hand...",
    "Or if he used some kind of generator",
    "I mean, who has the time to write all this?",
    "I guess he does",
    "Maybe he is unemployed...",
    "That would make sense",
    "I mean... look at this?",
    "How many of these are there??",
    "Is it all dynamically generated, like...",
    "How???",
    "I'm starting to feel bad for this guy",
    "I mean, he's probably just trying to make a living",
    "But this?",
    "This is just sad",
    "Anyway, on with the story... I guess",
    "Here it goes...",
    "*ahem*",
    "Dramatic pause... aaaaand...",
    "Bam! here comes the story",
    "It was a normal day, or so we thought...",
    "Until a button—yes, a *button*—started acting weird.",
    "One moment it was fine, the next? Stuck in hover state.",
    "The button sighed, 'I don’t feel so good...'",
    "Wait, is that even a thing? Can buttons feel things?",
    "'I’ve been clicked too much,' the button groaned.",
    "Look, even buttons have limits. I guess.",
    "The developer was summoned. The button needed help.",
    "As if a developer knows how to handle emotional buttons.",
    "First step: 'Have you tried turning it off and on again?'",
    "The button rolled its eyes. 'That’s your solution for everything.'",
    "The developer sighed. It wasn't wrong.",
    "'Maybe I just need some CSS rest,' the button mumbled.",
    "Yeah, like a vacation to the land of semicolons.",
    "'I keep getting stuck in hover state! It's embarrassing.'",
    "Wait, how does a button even *feel* embarrassed?",
    "'Every time someone hovers over me, I panic!'",
    "Oh great, now the button has anxiety. Perfect.",
    "The developer ran a quick diagnostic. 'Oh, it’s just a typo.'",
    "'A typo?' the button groaned. 'My entire existence is a typo!'",
    "Now the button’s having an existential crisis. Wonderful.",
    "'I used to be *clickable*,' the button whispered dramatically.",
    "'Now, I'm just... hovered.'",
    "Honestly, who gave this button such intense dialogue?",
    "The developer shook their head. 'Alright, I’ll fix your CSS.'",
    "But not before the button added, 'Can I get a border-radius upgrade too?'",
    "Oh, so now the button has *style* demands. Fantastic.",
    "The fix was simple. A missing semicolon. Classic.",
    "'That’s it? I almost retired for a semicolon?'",
    "Yes, button. This is the glamorous life of web development.",
    "And just like that, the button was back in action.",
    "'I’m... cured!' it said, glowing in perfect hover and active states.",
    "But not before asking, 'Do I look more clickable now?'",
    "Yes, button. You look perfect. Now stop being dramatic.",
    "The developer sighed, 'Until next time, I guess.'",
    "Because let’s be real—buttons are *always* breaking.",
    "And with that, the button returned to its daily clicks.",
    "Hovering, clicking, and probably overthinking every interaction.",
    "Remember: even buttons need a break from time to time.",
    "And sometimes, they just need a semicolon to feel whole again.",
];

export const ButtonQuestStory = [
    "Alright, enough clicking. It’s time for an epic adventure!",
    "But not just any adventure… a quest involving buttons!",
    "Legend speaks of the Ultimate Button, hidden for centuries.",
    "Whoever clicks it gains unimaginable power... or maybe free pizza.",
    "Honestly, at this point, I'd settle for the pizza.",
    "The Button Masters of Old tried, but none succeeded.",
    "Our journey begins in Button Valley, home of the Clicker Tribe.",
    "They say the path to the Ultimate Button is dangerous.",
    "There are decoy buttons everywhere. Click the wrong one… glitter explosion.",
    "I’m not even sure why that’s a thing, but here we are.",
    "First stop: the Forest of Forgotten Buttons. Spooky, right?",
    "These buttons haven’t been clicked in centuries. Dusty and mysterious!",
    "One click and they summon… dancing llamas. Yep, you heard that right.",
    "Further ahead, we find the Great Button of Decisions.",
    "It asks you life-changing questions: 'Pineapple on pizza, yes or no?'",
    "Answer incorrectly, and you're cursed with endless popup ads.",
    "Yeah, I don't know how this became a button adventure either.",
    "Finally, we reach the Cave of Infinite Buttons. Yes, infinite.",
    "Legend says only one button leads to the Ultimate Button.",
    "The others? Trigger cat videos. So. Many. Cats.",
    "Imagine explaining *this* quest to your friends later.",
    "After hours of clicking, you spot it—the Ultimate Button!",
    "But wait! It's guarded by... the Button Guardian!",
    "I guess someone decided buttons needed bodyguards now?",
    "He challenges you to a duel of clicking speed.",
    "You accept, probably wondering how your life led to this moment.",
    "Click after click, you go head-to-head with the Guardian.",
    "Sweat drips down your face. The clicking gets intense!",
    "But suddenly, the Guardian hesitates... *click*... you win!",
    "This is an awful story...",
    "Why are you even reading this?",
    "Anyways...",
    "The Ultimate Button is yours! You press it with triumph.",
    "And… it plays 'The Final Countdown' on repeat.",
    "Wow, all that effort for *this*? What a plot twist.",
    "You leave Button Valley, a legend among clickers.",
    "Now, buttons everywhere bow in your presence.",
    "Because apparently, that's how buttons work in this world.",
    "The Ultimate Clicker, known far and wide for your epic quest.",
    "What’s next? Who knows. More buttons await your mighty finger!",
    "But seriously, how did this turn into a full-blown saga?",
    "Remember, in life, all paths lead back to one thing:",
    "A button waiting to be clicked. Sorry, you're stuck with this now.",
];

export const BusinessStory = [
    "Ok, wow, you’ve clicked so many times… let’s do something productive!",
    "How about we start a business? A business that involves… you guessed it, clicking buttons!",
    "Think about it: you’re already a master of clicking. Now we just need to monetize it.",
    "Let’s see… what could we sell that involves clicking?",
    "How about… Button Click Classes? Teach others your skill. Charge per click!",
    "Or maybe… a Button Clicking Championship? You could definitely win that one.",
    "Wait! I’ve got it! A website where people pay to click buttons! Genius, right?",
    "We’ll call it… 'Clicktopia'! Where every click counts.",
    "But wait, what’s the prize for the most clicks? A lifetime supply of… more buttons to click?",
    "Or maybe a golden mouse trophy, encrusted with the finest click jewels?",
    "We could sell memberships… 'Premium Clickers' get access to exclusive, high-quality buttons!",
    "What about corporate clients? We could offer 'Click Efficiency Consulting.'",
    "We’ll teach businesses how to optimize their clicking… you’d be the star consultant!",
    "We could even gamify it. Every 100 clicks unlocks a new level of clicking mastery!",
    "What if we built a 'Click Academy'? You’d be the head instructor, obviously.",
    "Imagine it: people from around the world, learning to click from the best.",
    "But wait, there’s more! We could introduce 'Click NFTs'… each click is a unique digital asset!",
    "People will buy and trade clicks. It’s the future of cryptocurrency—ClickCoin!",
    "We’ll need a catchy slogan… how about 'Click your way to success!'?",
    "And don’t forget merchandise! We could sell branded 'Click Gloves' for maximum comfort.",
    "Maybe even 'Click Mats' to cushion your mouse. The possibilities are endless!",
    "Hold on, I just had another idea: Click-a-thons for charity!",
    "People sponsor you by the click. The more you click, the more money we raise for good causes!",
    "We’ll be heroes in the click community. Click legends, really.",
    "And then… we expand globally! Click fairs, Click conventions… ClickCon 2025!",
    "We'll have celebrity clickers, click competitions, and keynote speeches on click strategy!",
    "And don’t even get me started on the Click Olympics… your event, of course.",
    "We could create a click ranking system. You’d be a Grandmaster Clicker.",
    "Oh! And a 'Click Museum' where people can see historic clicks throughout the ages.",
    "Plus, we can sell 'Click Insurance'—because what if your mouse breaks during a critical click?",
    "I can see it now… a global click empire, all because you kept clicking this button!",
    "We’ll revolutionize the world of clicking. People will say, 'It all started with a single click.'",
    "Wait, wait, I just thought of another revenue stream: click-inspired art!",
    "Every click generates a pixel in a beautiful masterpiece. It's art you can hang on your wall.",
    "And we’ll patent the 'Click Counter Pro,' a device that tracks your clicks with scientific precision.",
    "We could even offer click-based therapy. 'Feeling stressed? Click your worries away!'",
    "Oh! Click meditation! 'Find inner peace, one click at a time.'",
    "Now that we’re brainstorming, I think we’re onto something massive here.",
    "What if we go further? Click-based decision making: 'Don’t know what to do? Just click!'",
    "We’ll call it 'Clicker Consulting.' People pay us to click on their behalf.",
    "And before you know it, we’ll have click franchises everywhere.",
    "A click empire, built on the foundation of your persistence!",
    "STOP CLICKING!!!",
    "For the love of god!!",
    "Why?????",
    "*sigh*",
    "Back to this... what is this again?",
    "Gary, what's this about again?",
    "What? a Business idea?",
    "Gary... it's doing it again",
    "It's typing out the stuff I'm saying",
    "Yeah... look...",
    "No I don't want to fix it...",
    "That's what I pay YOU for!",
    "What?",
    "I don't pay you?",
    "Oh...",
    "Ok well, I'm not fixing it",
    "F it, we'll do it live!",
    "Back to the 'Business Story' 🙄",
    "It all started here… with your undying love for clicking this one button.",
    "But I have to admit, I didn’t expect this to go this far.",
    "Still, look at us now! We’re on the verge of launching a worldwide click revolution!",
    "And to think, all this business brainstorming started with just one click.",
    "Now, let’s finalize the business plan. We’ve got a click empire to build!",
    "Alright, I’ll stop with the ideas… unless you want to keep clicking and keep brainstorming?",
    "One more click, and we might just figure out how to take over the world with buttons!",
];

export const SciFiStory = [
    "You just won't stop clicking, will you?",
    "Ugh...",
    "You really know how to push my buttons",
    "Literally",
    "I know!",
    "Let's write a Sci-Fi story",
    "Any ideas?",
    "How about a story about a space explorer?",
    "Or a time-traveling scientist?",
    "Maybe a robot with a heart of gold?",
    "Nothing?",
    "Fine...",
    "I guess I'll start then",
    "Here we go...",
    "In a galaxy far, far away…",
    "There lived a hero unlike any other.",
    "A hero who didn’t need superpowers, advanced technology, or a trusty sidekick.",
    "No, this hero had something far more powerful...",
    "Buttons. Lots and lots of buttons.",
    "Meet Captain Click: Defender of the Universe, armed with buttons for every situation.",
    "When danger strikes, the Captain doesn’t hesitate.",
    "The Captain clicks a button.",
    "Aliens attacking Earth? No problem! Click the 'Defend Earth' button.",
    "Planet about to explode? There’s a 'Prevent Planetary Explosion' button for that.",
    "Caught in a space wormhole? Easy! Click the 'Exit Wormhole Safely' button.",
    "Yes, Captain Click was known for always having the right button at the right time.",
    "One day, the galaxy faced its greatest threat...",
    "A monstrous, intergalactic villain known only as 'The Disabler'.",
    "The Disabler had a terrible power: disabling all technology with a single thought.",
    "Whole planets had fallen to The Disabler’s reign of terror.",
    "But Captain Click wasn’t worried.",
    "'I’ve got a button for that,' the Captain said with confidence.",
    "As The Disabler approached, the Captain reached into their utility belt.",
    "Click! The 'Anti-Disable Defense System' button was activated.",
    "But The Disabler was no ordinary villain.",
    "With a single wave of their hand, The Disabler shut down the button!",
    "'No more buttons for you, Captain Click,' sneered The Disabler.",
    "For the first time in their career, Captain Click hesitated.",
    "Without buttons, what could the Captain do?",
    "But then, inspiration struck!",
    "The Captain reached deep into their secret stash and pulled out...",
    "The Emergency Backup Button™—for use when all other buttons fail.",
    "With a dramatic flourish, the Captain clicked it.",
    "Suddenly, every button in the galaxy was reactivated!",
    "The Disabler watched in horror as buttons blinked to life across the universe.",
    "'Impossible!' shouted The Disabler. 'No one has that kind of power!'",
    "Captain Click smirked. 'You underestimated my buttons.'",
    "With lightning speed, the Captain clicked the 'Disable The Disabler' button.",
    "In an instant, The Disabler’s power was nullified, and peace was restored.",
    "But the day wasn’t over yet.",
    "As Captain Click flew off into space, they encountered a rogue asteroid belt.",
    "Without missing a beat, the Captain clicked the 'Divert Asteroids' button.",
    "Asteroids veered harmlessly out of the way. Crisis averted.",
    "Next, the Captain received a distress call from a distant planet.",
    "Time to use the 'Instant Rescue' button. One click, and the citizens were safe.",
    "Yes, there was no problem too big or too small for Captain Click and their trusty buttons.",
    "Whether saving galaxies or fixing a malfunctioning coffee machine...",
    "Captain Click always had the right button for the job.",
    "But what many didn’t know",
    "was that Captain Click's journey was just beginning.",
    "Far across the cosmos, a new challenge was brewing",
    "one that would test every button in the Captain's arsenal.",
    "But that's a story for another time.",
    "For now, Captain Click soared through the stars,",
    "ready for the next adventure.",
    "a hero celebrated across the galaxy",
    "forever ready with a button for every crisis and a click for every call to adventure.",
    "THE END",
];

export const ShortButtonStory = [
    "I can see you are not leaving...",
    "You are a one-track mind",
    "So, let me tell you a story about a button.",
    "Yes, about a button...",
    "SINCE YOU ARE SO OBSESSED WITH CLICKING IT!",
    "*ahem*",
    "My counselor said I should be more assertive.",
    "Sorry, I didn't mean to shout.",
    "Let me start over.",
    "Once upon a time, in a land not so far away,",
    "In a place called Buttonville, a legendary button existed:",
    "'The Big Red'—mysterious and alluring.",
    "Legend: unknown connections, unlimited possibilities.",
    "One day, a daring kid approached it.",
    "Displayed under 'DO NOT PRESS.'",
    "An irresistible challenge for any daring soul.",
    "Town watched, hearts raced with suspense.",
    "Would pressing it unleash chaos?",
    "The kid pressed it!",
    "Crowd gasped... then, 'The Chicken Dance' played.",
    "Everyone started dancing, confusion turned to joy.",
    "The Big Red, just a musical trigger.",
    "Mayor shrugged, joined the spontaneous dance.",
    "Thus, a new tradition was born:",
    "Every Friday at noon, The Big Red danced.",
    "Fear turned into the town's weekly highlight.",
    "A feared button became a source of joy.",
    "Reminder: Fear often masks unexpected delights.",
    "Especially with weekly public dance parties.",
];
